### ISSUE TITLE
分享網址無法複製 (macOS Chrome)

### ISSUE THREAD

**Issue by x3388638** [snsd0805/NCNU_Course#10]
macOS Chrome 沒辦法選取 & 複製 alert 的內容
<img width="461" alt="截圖 2021-01-19 22 15 37" src="https://user-images.githubusercontent.com/8147952/105047214-febf0500-5aa4-11eb-9627-1be89b47b9f7.png">

**Comment by snsd0805** [comment]
謝謝學長！！已經有修復這個問題！
