### ISSUE TITLE
Course Detail & Credit Counter

### ISSUE THREAD

**Issue by DavMar1995** [snsd0805/NCNU_Course#15]
In my opinion, maybe it would be better to open the course detail with another page, cause most of the users would view this site via NB or PCs. (I didn't test what would happened if direct to the detail page without saving the schedule, maybe this would be a point need to consider). Besides, if there is also an icon or button to open the detail of the each course in the schedule, it would be perfect.

Here, I would like to make a wish. If there's a function could let user insert their credit in each field would be very helpful for users, cause users don't need to count how many credits they already got every semester.

By the way, although I am going to graduate this summer, but I think this tool is VERY USEFUL, thanks for your effort.

**Comment by snsd0805** [comment]
不好意思，我在這邊用中文回覆！

首先先感謝學長的建議！！關於幾點建議先回覆給您，我後續再做功能上的新增！

1. open the course detail with another page： 這個我這一兩天就會馬上做修正
2. button to open the detail in the schedule：會再思考怎麼樣的排版或方法可以將這個功能美美的新增進去！
3. let user insert their credit in each field：以前有想過這個功能，但是以前我的爬蟲技巧還沒辦法爬到教務系統裡有紀錄課程學分數的那一頁，這個過一陣子會新增上去！

非常謝謝學長給的建議！真的獲得非常好的想法！

**Comment by x3388638** [comment]
FYI
`https://ccweb.ncnu.edu.tw/student/aspmaker_course_opened_detail_viewview.php?showdetail=&year={year}&courseid={courseId}&_class={courseClass}&modal=0`
裡面有學分數

e.g: https://ccweb.ncnu.edu.tw/student/aspmaker_course_opened_detail_viewview.php?showdetail=&year=1092&courseid=991024&_class=0&modal=0

**Comment by snsd0805** [comment]
Credit coute: d289a7

**Comment by snsd0805** [comment]
button to open the detail in the schedule: ed7bad4

**Comment by snsd0805** [comment]
目前這個 issue 看起來都有實做完成，我先 close
感謝學長們的幫忙
