### ISSUE TITLE
用課程名稱來刪除會出事

### ISSUE THREAD

**Issue by x3388638** [snsd0805/NCNU_Course#17]
![image](https://user-images.githubusercontent.com/8147952/105625748-38f22300-5e66-11eb-9303-136ec2ca4067.png)

雖然極少課名會重複也極少 use case 會遇到

**Comment by snsd0805** [comment]
謝謝學長的提醒，這個問題以前有遇過，但是想說發生機率太低就偷懶沒有去修正 XD

我這一兩天就會趕快做修正！！

**Comment by vincentinttsh** [comment]
修正中

**Comment by vincentinttsh** [comment]
看起來修正完畢 @snsd0805

**Comment by snsd0805** [comment]
謝謝兩位學長！ @x3388638 @vincentinttsh
