### ISSUE TITLE
Error Information of Course

### ISSUE THREAD

**Issue by DavMar1995** [snsd0805/NCNU_Course#20]
I would like to tell a necessary problem, here comes a situation both me and my friends occurred.
We are interest in React, so all of us planed to sign up for 前端程式設計, which is provided by 資工系, in this semester. On this site, we found the time of this course is 4fgh, but actually the time provided by education system is 2fgh, in addition, we need to re-plan our course.
In my option, maybe this kind of situation happened is because of conflict between the old data and new data, hope you could find a way to solve this problem.

**Comment by snsd0805** [comment]
抱歉這幾天沒有注意到 issue。

時間錯誤的原因應該就是該課程教師在「我從教務系統爬取資料」後的這段時間有做課程時間的修改。


但，因為從教務系統爬取下來的資料在「通識領域」的資料不甚完整，課程的 json 檔必須經過部份手動修改後才會是正確的。若要達成真正的自動更新，我目前有一些想法，等我過一陣子就會做功能的新增。

現階段仍然會以手動修改時間為主，我會另外開一個 issue #21 讓大家回報。

**Comment by snsd0805** [comment]
PS.  雖說會先手動修改，但是因為運行的伺服器是我家中的 Raspberry Pi 裝置，因為近日遇到一些問題我目前無法連線進去做修正，這週末回到家後才會進行修正。

謝謝學長回報！

**Comment by snsd0805** [comment]
雖然還是有必須人工處理的部份，但已經可以自動化處理分類問題
