### ISSUE TITLE
一堆問題

### ISSUE THREAD

**Issue by molaboon** [snsd0805/NCNU_Course#6]
1. 資工系應該放在第一個選項ㄅ
2. 新增必修，選修的部分(the last)
3. 當我碰到課程的時候，課表浮出浮水印。

**Comment by snsd0805** [comment]
1. 一開啟網頁，預設的就是資工系拉 哈哈！

2. 必選修好像非必要，怕會造成版面混亂，不過以後有機會的話會想其他方法加上去。

3. OK， 我先 assign 給自己，有時間的時候就會加上去。

**Comment by snsd0805** [comment]
1. 3. 功能已有

2. 為了版面先選擇不添加，況且學校似乎沒有必選修相關資料，似乎只能從各系哪邊取得資料，難度非常高。

因此先 closed issue
